// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "x7fixUC32pwGo4JVp0ZOgy0xUFxCB0z1j73UvW2CVGlPcjqBaLk5Nsheflh8DRg3eSlque";
}
}
}

