// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "ejoazLzjoNFedI3rRdCenQaPqStK385i7uMDdQyH1BeaE1pb5FZQOkhyWs6ADdpn40TrXf";
}
}
}

